### ISSUE TITLE
how to understanding the model_size?

### ISSUE THREAD

**Issue by CangHaiQingYue** [LevinJ/SSD_tensorflow_VOC#11]
I download the ssd_300_vgg.ckpt,  it's about 100M.
But when I initialize the ssdnet randomly I get a 300M model_cpkt.
And when I restore from the ssd_300_vgg.ckpt, and finetune the network, I also get a 300M model.
How to understanding this? can you help me.

**Comment by LevinJ** [comment]
Hi, where did you get the ssd_300_vgg.ckpt model file, which is 100M.

Could it be this version of the model is used only for inference and have all training related stuff in the graph remvoed, and thus have a smaller footprint?

**Comment by CangHaiQingYue** [comment]
I got ckpt from https://github.com/balancap/SSD-Tensorflow. I did not know whether it is used only for inference or not. Besides I want know will slim model be useless in the feature? Cause the official said they only support keras. 
Finally，may I ask if I can follow your wechat，I guess you are Chinese...（my number is   921156593）

**Comment by LevinJ** [comment]
Hi I had some experience with Keras, yes, it's very easy to use, and is indeed very good.
I am aware that Keras is now part of stardard tensorlfow distribution, but I think the same applies to slim.

In my experience, Slim allows us more flexibility in terms of customizing/reusing exising pretrained models,  it has has a fantastic growing computer vision related model zoo, which comes handy if we are to work in this area.

Will add your wechat now :)

**Comment by CangHaiQingYue** [comment]
yes！ Please。
