### ISSUE TITLE
How to get single image detections?

### ISSUE THREAD

**Issue by cravisjan97** [LevinJ/SSD_tensorflow_VOC#2]
I am still performing the training of then ssd weights and I am yet to fine tune the vgg net. How did you obtain the single image detections(as ahown in your README file)?

**Comment by LevinJ** [comment]
Hi @cravisjan97 , to perform detection on single image, I used the demp.py script under demo folder.  We can specify which image to detect by setting the `image_name` variable in the script.  Does this answer your question?

**Comment by cravisjan97** [comment]
Thanks @LevinJ. It worked
