### ISSUE TITLE
ohem

### ISSUE THREAD

**Issue by liuhengli** [LevinJ/SSD_tensorflow_VOC#9]
Your project very good, Do you consider joining OHEM in your project

**Comment by LevinJ** [comment]
Thanks. Can you explain a bit what you mean by "OHEM".

**Comment by CangHaiQingYue** [comment]
@liuhengli Object Detectors with Online Hard Example Mining? I think OHEM already in the code.

**Comment by liuhengli** [comment]
I read this project not found, can yo tell me where it is?

**Comment by liuhengli** [comment]
@CangHaiQingYue

**Comment by CangHaiQingYue** [comment]
@liuhengli I'm sorry that in SSD original paper，using the hard negative mining(not OHEM). 
Otherwise, paper use 'Matching strategy' + 'Hard negative mining' instead of OHEM. you can see them is code "ssd.py (def __tf_ssd_bboxes_encode_layer()) in Line 667, and Line 896".

**Comment by liuhengli** [comment]
thanks
